steps:
  - name: 'gradle:8.14.3-jdk21'
    args: ['./gradlew','clean','build','-x','test']
#    volumes:
#      - name: 'gradle-cache'
#        path: /root/.gradle
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/dockerapp-1/dockerapp:$SHORT_SHA',
      '.'
    ]
      # Optional Docker cache inside this step
#    volumes:
#      - name: 'docker-cache'
#        path: /root/.docker-cache


images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/dockerapp-1/dockerapp:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
