steps:
  - name: 'gradle:8.14.3-jdk21'
    args: ['./gradlew', 'build']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/dockerapp-1/dockerapp:$SHORT_SHA',
      '.'
    ]

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/dockerapp-1/dockerapp:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
